<a href="https://colab.research.google.com/github/vlkumar-859/AI_ML/blob/master/Untitled11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [60]:
df['Altitude'].mean()
min(l['Altitude'])
l=df.head()
l

   Latitude ° Latitude  ...  Wireless Power Zero-Space Computing
0           0        S  ...           False                 True
1           0        S  ...           False                False
2           0        S  ...           False                False
3           0        S  ...           False                False
4           0        S  ...           False                 True

[5 rows x 79 columns]

In [61]:
min(l['Altitude'])

-1160

In [62]:
l['Altitude'].mean()

-1067.6

In [65]:
df=pd.read_csv("/content/edited MapData-Evans-GP-Flatten.csv")
df.head(20)

    Unnamed: 0 Latitude  Longitude °  ... Dust Storms Meteors  Cold Waves
0            0        S            0  ...           1       4           1
1            0        S            1  ...           1       4           1
2            0        S            1  ...           2       4           1
3            0        S            2  ...           1       4           1
4            0        S            2  ...           3       4           1
5            0        S            3  ...           1       4           1
6            0        S            3  ...           3       4           1
7            0        S            4  ...           1       4           1
8            0        S            4  ...           3       4           1
9            0        S            5  ...           1       4           1
10           0        S            5  ...           3       4           1
11           0        S            6  ...           2       4           1
12           0        S            6  ...           3       3           1
13           0        S            7  ...           3       4           1
14           0        S            7  ...           3       3           1
15           0        S            8  ...           3       4           1
16           0        S            8  ...           3       3           1
17           0        S            9  ...           3       4           1
18           0        S            9  ...           3       3           1
19           0        S           10  ...           3       4           1

[20 rows x 16 columns]